### PR TITLE
feat: add '?' key in order to show help informations

### PR DESCRIPTION
**Pull request by LinPr**
Just like lazygit, when user press '?' key, it prompt a help interface which shows the keybindings,. so I add some code the impliment the similar feature in lazysql. And after testing, it works in lazysql now .

And also, I modify the README.md to let users know this feature.

Well, I review some of the original code and rewrite some code to make it more readable, but I did't affect any of the major function of lazysql, so it is safe to merge into the main branch

### CODE REVIEW

**Comment by jorgerojas26** [comment]
While this is a really good feature, i think i don't like the UI proposed in this PR. I would like to see the keybindings in maybe like a table, where the text is justified and ordered, just like how Github shows it in the readme. Can you improve the UI?

**Comment by LinPr** [comment]
OK ，I see, I will try to improve it,thanks for replying!

**Comment by LostbBlizzard** [comment]
Is this still being worked on?

**Comment by LinPr** [comment]
> Is this still being worked on?

- well，I am sorry for that, cause I was busy with my job, so I didn't have many time on open source project 😅, if you have any interest in this issue, you can try to continue with this problem bro !

**Comment by LostbBlizzard** [comment]
> > Is this still being worked on?
> 
> * well，I am sorry for that, cause I was busy with my job, so I didn't have many time on open source project 😅, if you have any interest in this issue, you can try to continue with this problem bro !

I'll try to i'll make a pull request if i had any luck.

**Comment by jorgerojas26** [comment]
Closed in favor of #95

**Pull request closed without merging**
