### PR TITLE
sql injection

### PR DESCRIPTION
**Pull request by ccoVeille**
- **ci: enable security and SQL linters**
- **ci: enable identical-branches on revive linter**

Related tthe following issue as it reveals some SQL injection issues
- #80

### CODE REVIEW

**Comment by ccoVeille** [comment]
Here is a PR to show the current issues in the code

Please review the errors, then push PR on my branch to fix them

```
drivers/mysql.go:210:35: G202: SQL string concatenation (gosec)
	rows, err := db.Connection.Query("SHOW INDEX FROM " + table)
	                                ^
drivers/mysql.go:255:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("SELECT * FROM %s s LIMIT %d,%d", table, offset, defaultLimit)
	        ^
drivers/mysql.go:271:24: G201: SQL string formatting (gosec)
		queryWithoutLimit := fmt.Sprintf("SELECT COUNT(*) FROM %s %s", table, where)
		                    ^
drivers/mysql.go:358:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("UPDATE %s SET %s = \"%s\" WHERE %s = \"%s\"", table, column, value, primaryKeyColumnName, primaryKeyValue)
	        ^
drivers/mysql.go:367:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("DELETE FROM %s WHERE %s = \"%s\"", table, primaryKeyColumnName, primaryKeyValue)
	        ^
drivers/postgres.go:348:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("SELECT * FROM %s s LIMIT %d OFFSET %d", table, defaultLimit, offset)
	        ^
drivers/postgres.go:364:24: G201: SQL string formatting (gosec)
		queryWithoutLimit := fmt.Sprintf("SELECT COUNT(*) FROM %s %s", table, where)
		                    ^
drivers/postgres.go:412:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("UPDATE %s SET %s = '%s' WHERE \"%s\" = '%s'", table, column, value, primaryKeyColumnName, primaryKeyValue)
	        ^
drivers/postgres.go:420:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("DELETE FROM %s WHERE \"%s\" = '%s'", table, primaryKeyColumnName, primaryKeyValue)
	        ^
drivers/sqlite.go:130:35: G202: SQL string concatenation (gosec)
	rows, err := db.Connection.Query("SELECT sql FROM sqlite_master WHERE type='table' AND name = '" + table + "'")
	                                ^
drivers/sqlite.go:260:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("SELECT * FROM %s s LIMIT %d,%d", table, offset, defaultLimit)
	        ^
drivers/sqlite.go:276:24: G201: SQL string formatting (gosec)
		queryWithoutLimit := fmt.Sprintf("SELECT COUNT(*) FROM %s %s", table, where)
		                    ^
drivers/sqlite.go:368:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("UPDATE %s SET %s = \"%s\" WHERE %s = %s;", table, column, value, primaryKeyColumnName, primaryKeyValue)
	        ^
drivers/sqlite.go:375:11: G201: SQL string formatting (gosec)
	query := fmt.Sprintf("DELETE FROM %s WHERE %s = \"%s\"", table, primaryKeyColumnName, primaryKeyValue)
	        ^
drivers/postgres.go:598:2: unhandled-error: Unhandled error in call to function database/sql.DB.Close (revive)
	db.Connection.Close()
	^
drivers/mysql.go:43:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query("SHOW DATABASES")
	                               ^
drivers/mysql.go:63:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf("SHOW TABLES FROM `%s`", database))
	                               ^
drivers/mysql.go:88:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf("DESCRIBE %s", table))
	                               ^
drivers/mysql.go:130:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf("SELECT CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE where TABLE_SCHEMA = '%s' AND TABLE_NAME = '%s'", database, tableName))
	                               ^
drivers/mysql.go:172:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf("SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_COLUMN_NAME, REFERENCED_TABLE_NAME FROM information_schema.KEY_COLUMN_USAGE where REFERENCED_TABLE_SCHEMA = '%s' AND REFERENCED_TABLE_NAME = '%s'", database, tableName))
	                               ^
drivers/mysql.go:265:43: rows.Err must be checked (rowserrcheck)
	paginatedRows, err := db.Connection.Query(query)
	                                        ^
drivers/mysql.go:318:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(query)
	                               ^
drivers/postgres.go:66:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query("SELECT datname FROM pg_database;")
	                               ^
drivers/postgres.go:96:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf("SELECT table_name, table_schema FROM information_schema.tables WHERE table_catalog = '%s'", database))
	                               ^
drivers/postgres.go:126:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf("SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns WHERE table_catalog = '%s' AND table_schema = '%s' AND table_name = '%s' ORDER by ordinal_position", database, tableSchema, tableName))
	                               ^
drivers/postgres.go:166:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf(`
	                               ^
drivers/postgres.go:222:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf(`
	                               ^
drivers/postgres.go:279:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf(`
	                               ^
drivers/postgres.go:358:43: rows.Err must be checked (rowserrcheck)
	paginatedRows, err := db.Connection.Query(query)
	                                        ^
drivers/postgres.go:440:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(query)
	                               ^
drivers/sqlite.go:45:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query("SELECT file FROM pragma_database_list WHERE name='main'")
	                               ^
drivers/sqlite.go:67:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query("SELECT name FROM sqlite_master WHERE type='table'")
	                               ^
drivers/sqlite.go:89:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(fmt.Sprintf("PRAGMA %s.table_info(%s)", database, table))
	                               ^
drivers/sqlite.go:171:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query("PRAGMA foreign_key_list(" + table + ")")
	                               ^
drivers/sqlite.go:212:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query("PRAGMA index_list(" + table + ")")
	                               ^
drivers/sqlite.go:270:43: rows.Err must be checked (rowserrcheck)
	paginatedRows, err := db.Connection.Query(query)
	                                        ^
drivers/sqlite.go:326:34: rows.Err must be checked (rowserrcheck)
	rows, err := db.Connection.Query(query)
	                               ^
components/ResultsTable.go:175:4: identical-branches: both branches of the if are identical (revive)
			if i == 0 {
				tableCell.SetTextColor(tview.Styles.PrimaryTextColor)
			} else {
				tableCell.SetTextColor(tview.Styles.PrimaryTextColor)
			}
38 issues:
* gosec: 14
* revive: 2
* rowserrcheck: 22
```

**Comment by ccoVeille** [comment]
@jorgerojas26 One way to consider this PR is also to merge it as-is, and then to start fixing the issues with other PRs

**Comment by jorgerojas26** [comment]
> @jorgerojas26 One way to consider this PR is also to merge it as-is, and then to start fixing the issues with other PRs

Thanks for the PR.

I'm thinking of merging in #73 and do the fixing there. Makes sense?

**Comment by ccoVeille** [comment]
> > @jorgerojas26 One way to consider this PR is also to merge it as-is, and then to start fixing the issues with other PRs
> 
> Thanks for the PR.
> 
> I'm thinking of merging in #73 and do the fixing there. Makes sense?
> 
> 

Sure!

**Comment by jorgerojas26** [comment]
Closed in favor of #73

**Pull request closed without merging**
