### PR TITLE
fix(postgres): fixing postgres connection

### PR DESCRIPTION
**Pull request by KevenGoncalves**
This fix the problem of lazysql not opening a postgres connection because the missing dbName path 
#16

### CODE REVIEW

**Comment by KevenGoncalves** [comment]
> The main idea of this is to be able to connect to a specific database, but this PR does not handle that scenario, it only fixes the connection url being saved with the database name but when you connect to that url, the tree stills shows every database that lives in the server.
> 
> I think this only makes sense to merge if we could handle that scenario.

yes, the tree show all the databases but it doesn't allow you to see the data or select others databases, only the one is passed in the string connection

**Comment by jorgerojas26** [comment]
Yeah, but i think it would be confusing to be allowed to see other databases but not be able to interact with them. If i put a database in the connection string i would expect to only connect and see that specific database.

**Comment by KevenGoncalves** [comment]
> Yeah, but i think it would be confusing to be allowed to see other databases but not be able to interact with them. If i put a database in the connection string i would expect to only connect and see that specific database.

You are right, let me fix that and open the PR again

**Comment by KevenGoncalves** [comment]
@jorgerojas26  Done!.

Now only show the database that is passed in the dbName
Captura de Tela 2024-01-20 às 12 24 27

**Comment by jorgerojas26** [comment]
@KevenGoncalves awesome bro. I like that.

Can you please resolve the conflicts?. I will merge this.

**Comment by KevenGoncalves** [comment]
Let me try to fix it

**Comment by KevenGoncalves** [comment]
@jorgerojas26 Merge conflict fixed

**Pull request merged**
