### PR TITLE
adds mssql driver

### LINKED ISSUE #12: [feat]: MSSQL Support
As a user of lazygit, this would be perfect for me, if only it had MSSQL support.

### PR DESCRIPTION
**Pull request by FrauElster**
## Summary
Adds a mssql driver in drivers

## Changes
- adds drivers/mssql.go, the actual driver
- adds drivers/mssql_test.go, these tests are **not automated**, meaning you have to provide a database and set the tableName, databaseName and connection string. (It is pretty straight forward)
- adds compiler checks to each driver implementation to verify these implement the Driver interface
- adds mssql driver to components/ConnectionForm.go
- adds mssql driver to components/ConnectionSelection.go

## Related Issues
Fixes #12

### CODE REVIEW

**Comment by FrauElster** [comment]
Whopsie, forgot a big todo. Give me a moment.

**Comment by jorgerojas26** [comment]
Thank you for the PR. I'll check and test it a bit a come back with suggestion/merging.

**Comment by jorgerojas26** [comment]
I don't know much about mssql, but i created a docker instance, created a table named "test", i am able to connect to it and list all the "instances" and "tables", but when i select a table it shows the following error:

image


Any idea of why is this happening?

**Comment by FrauElster** [comment]
I will check on this as soon as I have time. 
I only have an already working remote database and since I am on M1 I cannot really have an local instance. 
As I said I will look into this. I am also preparing a PR with some more driver tests if you are interested.

**Comment by FrauElster** [comment]
Oh and I did not mention this yet: it's a great project you created here. Props for that. :)

**Comment by jorgerojas26** [comment]
> I will check on this as soon as I have time. I only have an already working remote database and since I am on M1 I cannot really have an local instance. As I said I will look into this. I am also preparing a PR with some more driver tests if you are interested.

I'm on M1 also, i just created a docker instance.



> Oh and I did not mention this yet: it's a great project you created here. Props for that. :)

Thank you very much, i love this project, i use it daily. I know it is not the best code (first go project), and it have bugs, but with the help of the community we can make this awesome.

Thanks for your time making this PR.

**Comment by jorgerojas26** [comment]
Hi,

above problem is indeed solved, but there's still something i noticed today. When you press "2" inside the table view to see the "Columns", it is empty.

image


Maybe there's a problem in the GetTableColumns function in the driver file.

**Comment by FrauElster** [comment]
So the problem is, that even though the drivers interface specifies the _GetTableColumns_ with the parameters _database_ and _table_, the _database_ is empty, whereas the _table_ is of format _database_._table_. 
Apparently I misunderstood the interface, but I think it should be refactored. There should always be a database and a table attribute. The table attribute should never have the database encoded into it.  Also I suggest a context.Context is passed, as described in https://pkg.go.dev/context.

I would love to make this a separate PR. For now I will always check if the table param contains a database and if so overwrite database param, I guess.
Change is comming up. 

If you have a way for private communication let me know. I would love to here what you say on the interface change. I am sure there is a reason that the database is encoded in the table param, that I just dont know about.

**Comment by jorgerojas26** [comment]
When i try to filter a table, the following error happens:

image



> Apparently I misunderstood the interface, but I think it should be refactored. There should always be a database and a table attribute. The table attribute should never have the database encoded into it. Also I suggest a context.Context is passed, as described in https://pkg.go.dev/context.

I agree that should be refactored

**Comment by JustBarnt** [comment]
@jorgerojas26 @FrauElster Was just curious if there had been any progress with this? I've been looking forward and following this project for a while, but my work only involves MSSQL so unfortunately I still can't use it. But I am looking very forward to when this MSSQL support is completed!

**Comment by jorgerojas26** [comment]
> @jorgerojas26 @FrauElster Was just curious if there had been any progress with this? I've been looking forward and following this project for a while, but my work only involves MSSQL so unfortunately I still can't use it. But I am looking very forward to when this MSSQL support is completed!

I think this PR is stuck, there has no been any progress in a while. I'll try to make the integration myself in a few days.

**Comment by JustBarnt** [comment]
@jorgerojas26 Awesome! I was just curious been following this since I had seen the initial PR and was curious as it did seem stuck. But thanks for all your work!

**Comment by FrauElster** [comment]
Sorry back from the oblivion. It have been super busy both at work and personal. 

If I remember correctly I was somewhat unhappy with the interface for the drivers, which sometimes passed the database.tablename, sometimes only tablename, sometimes nothing. This was the root cause of the problems at hand, and I started to refactor it...and got lost and distracted doing this. 

I would be happy if someone else takes over, this PR, if not my forecast is that in late october my situation gets a bit more calm and I can give it another try :)

**Comment by jorgerojas26** [comment]
> Sorry back from the oblivion. I have been super busy both at work and personal.
> 
> If I remember correctly I was somewhat unhappy with the interface for the drivers, which sometimes passed the database.tablename, sometimes only tablename, sometimes nothing. This was the root cause of the problems at hand, and I started to refactor it...and got lost and distracted doing this.
> 
> I would be happy if someone else takes over, this PR, if not my forecast is that in late october my situation gets a bit more calm and I can give it another try :)

It's ok :) yeah, the interface has been refactored to always receive the database name. I'll close this PR because there has been major refactors since opened. Thanks for the try :)

**Pull request closed without merging**
