### PR TITLE
Rename files to the more commenly used (in Go projects) snake_case

### PR DESCRIPTION
**Pull request by svanharmelen**
In addition renamed a few identifiers to follow the initialisms guideline:
https://go.dev/wiki/CodeReviewComments#initialisms

### CODE REVIEW

**Review by ccoVeille — APPROVED** [review]

**Comment by ccoVeille** [comment]
There is also new revive rule for validating variables name

Please add `var-naming` to the revive rules section of .golangci-lint

**Comment by svanharmelen** [comment]
Found an additional variable due to configuring the `var-naming` rule, so nice one @jorgerojas26 👍🏻

**Review by ccoVeille — APPROVED** [review]

**Comment by ccoVeille** [comment]
> Found two additional variables due to configuring the `var-naming` rule, so nice one @jorgerojas26 👍🏻

Nice one to me @ccoVeille , no ? 😂😅

**Comment by svanharmelen** [comment]
Oops... Yes, nice one @ccoVeille 😉

**Comment by jorgerojas26** [comment]
Hahaha good work guys.

**Review by ccoVeille — APPROVED** [review]

**Pull request merged**
